### ISSUE TITLE
macOS 10.14 Mojave Build Error

### ISSUE THREAD

**Issue by sjain882** [rehlds/ReGameDLL_CS#432]
EDIT: Made some progress... now it does this

```
* Where:
Script '/Users/sjain/Desktop/rg/shared.gradle' line: 1

* What went wrong:
Could not compile script '/Users/sjain/Desktop/rg/shared.gradle'.
> startup failed:
  script '/Users/sjain/Desktop/rg/shared.gradle': 1: expecting EOF, found ':' @ line 1, column 32.
     Script started on Sun Oct  6 10:15:20 2019
                                    ^
  
  1 error

```

MORE PROGRESS

The shared.gradle file just had two lines of logs in it, so i cleared it all, then ran again, but this:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sjain/Desktop/rg/dep/cppunitlite/build.gradle' line: 14

* What went wrong:
A problem occurred configuring project ':dep/cppunitlite'.
> Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
   > Could not find method createToolchainConfig() for arguments [shared library 'cppunitlite:debug:sharedLibrary'] on root project 'regamedll'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


```

***

Running on a completely clean install.

1. I installed homebrew in terminal.

2. Then I ran `brew install gradle`

3. Then I ran `brew install gcc`

4. restarted mac.

5. Clone and download this repo, extract. Navigated to this folder in terminal.

6. Ran `./gradlew --max-workers=1 clean -PuseGcc buildRelease`

7. Error:

```
sjains-Mac:rg sjain$ ./gradlew --max-workers=1 clean -PuseGcc buildFixes
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
##teamcity[buildNumber '5.11.0']

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sjain/Desktop/rg/shared.gradle' line: 47

* What went wrong:
A problem occurred configuring project ':dep/cppunitlite'.
> Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
   > Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.88 secs
```

Same happens if I use `./gradlew --max-workers=1 clean -PuseGcc buildFixes`

# Requirements:

```
sjains-Mac:~ sjain$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

sjains-Mac:~ sjain$ javac -version

javac 1.8.0_221
```

# Stacktrace:

```
sjains-Mac:rg sjain$ ./gradlew --max-workers=1 clean -PuseGcc buildFixes --stacktrace
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
##teamcity[buildNumber '5.11.0']

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sjain/Desktop/rg/shared.gradle' line: 47

* What went wrong:
A problem occurred configuring project ':dep/cppunitlite'.
> Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
   > Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':dep/cppunitlite'.
	at org.gradle.execution.TaskNameResolver.selfClosedTasksNode(TaskNameResolver.java:116)
	at org.gradle.execution.TaskNameResolver.hasTask(TaskNameResolver.java:128)
	at org.gradle.execution.TaskNameResolver.access$100(TaskNameResolver.java:38)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:195)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collect(TaskNameResolver.java:203)
	at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult.collectTasks(TaskNameResolver.java:191)
	at org.gradle.execution.TaskNameResolver.selectWithName(TaskNameResolver.java:61)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:87)
	at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:75)
	at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(CommandLineTaskParser.java:42)
	at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:44)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
	at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:48)
	at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:44)
	at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecuter.java:42)
	at org.gradle.execution.DefaultBuildExecuter.select(DefaultBuildExecuter.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception thrown while executing model rule: org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules#createNativeBinaries(org.gradle.platform.base.BinaryContainer, org.gradle.api.NamedDomainObjectSet<org.gradle.nativeplatform.NativeComponentSpec>, org.gradle.language.base.internal.registry.LanguageTransformContainer, org.gradle.nativeplatform.toolchain.internal.NativeToolChainRegistryInternal, org.gradle.platform.base.internal.PlatformResolvers, org.gradle.nativeplatform.BuildTypeContainer, org.gradle.nativeplatform.FlavorContainer, org.gradle.internal.service.ServiceRegistry, java.io.File, org.gradle.api.internal.project.taskfactory.ITaskFactory)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:555)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutations(DefaultModelRegistry.java:488)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:415)
	at org.gradle.model.internal.registry.DefaultModelRegistry.close(DefaultModelRegistry.java:374)
	at org.gradle.model.internal.registry.DefaultModelRegistry.closeRuleBinding(DefaultModelRegistry.java:582)
	at org.gradle.model.internal.registry.DefaultModelRegistry.toViews(DefaultModelRegistry.java:566)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:542)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutations(DefaultModelRegistry.java:488)
	at org.gradle.model.internal.registry.DefaultModelRegistry.transition(DefaultModelRegistry.java:415)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrMaybeLater(DefaultModelRegistry.java:237)
	at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrLater(DefaultModelRegistry.java:229)
	at org.gradle.execution.TaskNameResolver.selfClose(TaskNameResolver.java:101)
	at org.gradle.execution.TaskNameResolver.selfClosedTasksNode(TaskNameResolver.java:114)
	... 48 more
Caused by: java.lang.RuntimeException: Unknown native toolchain: org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRegistry$UnavailableNativeToolChain
	at shared_6yc08rvzp1jalxvvgpo893my8$_run_closure1.doCall(/Users/sjain/Desktop/rg/shared.gradle:47)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:159)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at build_6ta14e5h3n1d01nvgyaqanbjo.setupToolchain(/Users/sjain/Desktop/rg/dep/cppunitlite/build.gradle:14)
	at org.gradle.api.internal.BeanDynamicObject$GroovyObjectAdapter.invokeMethod(BeanDynamicObject.java:275)
	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at build_6ta14e5h3n1d01nvgyaqanbjo$_run_closure1_closure5_closure7_closure9.doCall(/Users/sjain/Desktop/rg/dep/cppunitlite/build.gradle:58)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
	at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
	at org.gradle.nativeplatform.internal.configure.DefaultNativeBinariesFactory.createNativeBinary(DefaultNativeBinariesFactory.java:56)
	at org.gradle.nativeplatform.internal.configure.DefaultNativeBinariesFactory.createNativeBinaries(DefaultNativeBinariesFactory.java:46)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.executeForEachFlavor(NativeComponentSpecInitializer.java:99)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.executeForEachBuildType(NativeComponentSpecInitializer.java:91)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.execute(NativeComponentSpecInitializer.java:69)
	at org.gradle.nativeplatform.internal.configure.NativeComponentSpecInitializer.execute(NativeComponentSpecInitializer.java:40)
	at org.gradle.nativeplatform.plugins.NativeComponentModelPlugin$Rules.createNativeBinaries(NativeComponentModelPlugin.java:166)
	at org.gradle.model.internal.method.WeaklyTypeReferencingMethod.invoke(WeaklyTypeReferencingMethod.java:101)
	at org.gradle.model.internal.inspect.DefaultModelRuleInvoker.invoke(DefaultModelRuleInvoker.java:37)
	at org.gradle.model.internal.inspect.MethodBackedModelAction.execute(MethodBackedModelAction.java:63)
	at org.gradle.model.internal.registry.DefaultModelRegistry.fireMutation(DefaultModelRegistry.java:552)
	... 60 more


BUILD FAILED

Total time: 4.746 secs
sjains-Mac:rg sjain$ 
```

**Comment by Juesto** [comment]
There's no Mac support listed anywhere.

Those errors look like it's expected.

Do you have Xcode toolchain installed?

**Comment by Nord1cWarr1or** [comment]
This is outdated — the Gradle build system (the `shared.gradle` / "Unknown native toolchain" stack) has been removed from the project; the build now goes through CMake/`build.sh` (Linux) and `msvc/ReGameDLL.sln` (Windows). macOS was never a supported build target in any case. Closing as completed.
